rootProject.name = 'osl'

ext {
    prjDir = 'projects'
}

logger.info('Scanning projects...')

//noinspection GrUnresolvedAccess, GroovyAssignabilityCheck
var projects = new File(rootDir, prjDir).listFiles()
logger.info('Projects found: {}', projects.toString())

for (var prj : projects) {
    var name = prj.getName()
    var modules = prj.list()

    for (var mod : modules)
        include "projects:${name}:${mod}"
}

logger.info('Finish including projects')
