[versions]
okhttp-v = "4.9.3"
cglib-v = "3.3.0"
math3-v = "3.6.1"
jocl-v = "2.0.5"
jsoup-v = "1.20.1"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp-v" }
cglib = { module = "cglib:cglib", version.ref = "cglib-v" }
math3 = { module = "org.apache.commons:commons-math3", version.ref = "math3-v" }
jocl = { module = "org.jocl:jocl", version.ref = "jocl-v" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup-v" }
